/** Vendor SaaS plan row (admin configuration + Add Vendor). Persisted under `vendorSubscriptions.plans` in Mongo site config. */
export type VendorSubscriptionPlanRow = {
  id: number;
  configName: string;
  name: string;
  description: string;
  monthlyPrice: number;
  yearlyPrice: number;
  commission: number;
  maxProducts: number | 'unlimited';
  maxTeamMembers: number | 'unlimited';
  maxOrders: number | 'unlimited';
  features: Record<string, boolean>;
  active: boolean;
  isDefault: boolean;
  icon: string;
  color: string;
};

export const DEFAULT_VENDOR_SUBSCRIPTION_PLANS: VendorSubscriptionPlanRow[] = [
  {
    id: 1,
    configName: 'PLAN_STARTER',
    name: 'Starter',
    description: 'Perfect for new vendors just getting started',
    monthlyPrice: 19,
    yearlyPrice: 190,
    commission: 20,
    maxProducts: 50,
    maxTeamMembers: 2,
    maxOrders: 300,
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: false,
      prioritySupport: false,
      advancedAnalytics: false,
      apiAccess: false,
      whiteLabelBranding: false,
      customReports: false,
    },
    active: true,
    isDefault: false,
    icon: 'Star',
    color: '#10B981',
  },
  {
    id: 2,
    configName: 'PLAN_BASIC',
    name: 'Basic',
    description: 'Essential features for growing businesses',
    monthlyPrice: 29,
    yearlyPrice: 290,
    commission: 15,
    maxProducts: 100,
    maxTeamMembers: 3,
    maxOrders: 500,
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: true,
      prioritySupport: false,
      advancedAnalytics: false,
      apiAccess: false,
      whiteLabelBranding: false,
      customReports: false,
    },
    active: true,
    isDefault: true,
    icon: 'Star',
    color: '#6B7280',
  },
  {
    id: 3,
    configName: 'PLAN_PROFESSIONAL',
    name: 'Professional',
    description: 'For established vendors scaling their business',
    monthlyPrice: 59,
    yearlyPrice: 590,
    commission: 12,
    maxProducts: 500,
    maxTeamMembers: 7,
    maxOrders: 1500,
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: true,
      prioritySupport: true,
      advancedAnalytics: true,
      apiAccess: false,
      whiteLabelBranding: false,
      customReports: true,
    },
    active: true,
    isDefault: false,
    icon: 'TrendingUp',
    color: '#3B82F6',
  },
  {
    id: 4,
    configName: 'PLAN_PREMIUM',
    name: 'Premium',
    description: 'Advanced features and priority support',
    monthlyPrice: 79,
    yearlyPrice: 790,
    commission: 10,
    maxProducts: 1000,
    maxTeamMembers: 10,
    maxOrders: 2000,
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: true,
      prioritySupport: true,
      advancedAnalytics: true,
      apiAccess: true,
      whiteLabelBranding: false,
      customReports: true,
    },
    active: true,
    isDefault: false,
    icon: 'Crown',
    color: '#8B5CF6',
  },
  {
    id: 5,
    configName: 'PLAN_ENTERPRISE',
    name: 'Enterprise',
    description: 'Unlimited access with dedicated support',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    commission: 5,
    maxProducts: 'unlimited',
    maxTeamMembers: 'unlimited',
    maxOrders: 'unlimited',
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: true,
      prioritySupport: true,
      advancedAnalytics: true,
      apiAccess: true,
      whiteLabelBranding: true,
      customReports: true,
    },
    active: true,
    isDefault: false,
    icon: 'Zap',
    color: '#A855F7',
  },
  {
    id: 6,
    configName: 'PLAN_CUSTOM_VIP',
    name: 'Custom VIP',
    description: 'Tailored plan for high-volume vendors',
    monthlyPrice: 149,
    yearlyPrice: 1490,
    commission: 7,
    maxProducts: 2000,
    maxTeamMembers: 15,
    maxOrders: 5000,
    features: {
      basicDashboard: true,
      productManagement: true,
      orderManagement: true,
      emailSupport: true,
      basicAnalytics: true,
      prioritySupport: true,
      advancedAnalytics: true,
      apiAccess: true,
      whiteLabelBranding: true,
      customReports: true,
    },
    active: true,
    isDefault: false,
    icon: 'Award',
    color: '#F59E0B',
  },
];
